version: '3.8'
services:
  postgres-db:
    image: postgres:latest
    restart: always
    container_name: pg_container
    environment:
        POSTGRES_DB: SeguridadProspeccion
        POSTGRES_USER: usuario_admin
        POSTGRES_PASSWORD: Password2024#
    volumes:
    - F:/docketVolumenes:/var/lib/postgresql/data
    ports:
    - "5432:5432"
  